import Head from 'next/head';
import Layout from '../components/Layout';
import styles from '../scss/Home.module.scss';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Layout home={true} className={styles.main}>
				Hello!
			</Layout>

			<footer className={styles.footer}></footer>
		</div>
	);
}
